services:
  postgres:
    image: postgres:16
    container_name: opus-postgres
    restart: always
    environment:
      POSTGRES_DB: opus_language
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - opus-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d opus_language"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opus-app
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres@postgres:5432/opus_language?schema=public
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - opus-network

networks:
  opus-network:
    driver: bridge

volumes:
  postgres-data:
